### ISSUE TITLE
Additional package needed? colorspace

### ISSUE THREAD

**Issue by sadamowi** [m-orton/Evolutionary-Rates-Analysis-Pipeline#11]
Hi Matt,

I am working with the Annelida branch. It seemed that RStudio expected me to install the package "colorspace" around line 157 of the code. Does that make sense? Should the command to install that package be added to the code?

Cheers,
Sally

**Comment by m-orton** [comment]
Figured it out i think! colorspace is a prerequisite package for plotly apparently:
http://stackoverflow.com/questions/38403279/new-r-user-having-problems-installing-and-running-plotly-package

**Comment by m-orton** [comment]
So ill add the colorspace package to the script.

**Comment by sadamowi** [comment]
OK thanks Matt. After that, I suggest to close this issue.

**Comment by sadamowi** [comment]
OK good. I see that is added. I will close this issue.
