### ISSUE TITLE
one more line needed for using muscle?

### ISSUE THREAD

**Issue by sadamowi** [m-orton/Evolutionary-Rates-Analysis-Pipeline#15]
Hi Matt,

I found I needed to add this around line 140 in order to move forward.

biocLite("muscle")

I didn't want to change anything directly in the code, and so I created an issue. If you agree, then please do go ahead and add that. Then, I think we can close this minor issue.

Thanks!

Cheers,
Sally

**Comment by m-orton** [comment]
Hi Sally, I agree, I will add this line to the code.

**Comment by sadamowi** [comment]
Hi Matt. Thanks for verifying this and adding the new line. I will close this issue.

Cheers,
Sally
