### ISSUE TITLE
Question for Matt: Can efficiency of outputting alignments be improved?

### ISSUE THREAD

**Issue by sadamowi** [m-orton/Evolutionary-Rates-Analysis-Pipeline#17]
Hi Matt,

Thank you for adding the code for outputting key interim alignments and the final trimmed alignments. Those lines of code have been very helpful for exploring the performance of the analysis.

This is not an urgent issue, and I think these extra steps are fine overall for these smaller phyla (for which we potentially expect more serious alignment problems). However, I'm wondering if there is a straightforward way to have the alignments exported without having to rerun them?

If there isn't a straightforward way to combine those steps, then don't worry about this. Thank you.

Cheers,
Sally

**Comment by m-orton** [comment]
Hi Sally, you are right, there is actually an easier way of outputting to Fasta format which I just figured out:
For example the first preliminary alignment could be:

alignmentPrelima <- DNAStringSet(alignment2[[1]])
writeXStringSet(alignmentPrelima, file="alignmentPrelima.fas", format="fasta", width=1500)

This allows us to avoid redoing alignments.
Im going to change each alignment with this code instead.

Best Regards,
Matt

**Comment by m-orton** [comment]
Script has been edited in the Annelida branch to output to Fasta each alignment of each class without redoing alignments.

Best Regards,
Matt

**Comment by sadamowi** [comment]
OK great. I think that would be a good idea for these alignments to be saved as part of the routine running of the script. Thank you very much for addressing this.

Best wishes,
Sally
