### ISSUE TITLE
Jacqueline will run the code on fish

### ISSUE THREAD

**Issue by sadamowi** [m-orton/Evolutionary-Rates-Analysis-Pipeline#18]
Hi Matt,

I have spoken with Jacqueline, and once we feel the Annelida pipeline is fairly stable, we can let her know. I think we are almost there!

Then, she will run the code on fish and check the interim steps. I think this would be really helpful to have another person read over and run the code and also check what it is doing. She is much more advanced in R coding than I am. Once she verifies performance, I will close this issue.

Cheers,
Sally

**Comment by m-orton** [comment]
Hi Sally, I think this is a good idea since Jacqueline has caught errors in my script the past. 

Thanks,
Matt

**Comment by sadamowi** [comment]
OK great!  I understand that Jacqueline is now formally invited to be a collaborator in github, and so she can create new issues for anything she finds. I will therefore close this thread.
