### ISSUE TITLE
Issue #1 - Notes on sequence length decision - 620 bp

### ISSUE THREAD

**Issue by sadamowi** [m-orton/Evolutionary-Rates-Analysis-Pipeline#2]
TEST - I suggest we type up notes about important analysis decisions and the reasons we made those decisions. I can type up our recent 620 bp decision. First, can you see this?

**Comment by m-orton** [comment]
Yes I can. Ok sounds good. In the future I will make more detailed notes with each commit I make. Also, I will make separate branches for the class level analysis and order level analysis. You can also make a separate branch for the pipeline to if there are any edits you want to make.

**Comment by sadamowi** [comment]
Notes about our decision to go with 620 bp as the main sequence length:
-Most primers used in DNA barcoding studies amplify a region that is 658 bp long (between the primers).
-At the ends, there is typically a short section that is only covered by one of the two chromatograms. Also, Taryn Athey's MSc thesis showed the low-frequency variants are more common near the ends, suggesting that sequencing and sequence editing errors are concentrated there. Therefore, we elected to go with a light trimming at each end. Symmetrical trimming (19 bp per end for full-length barcodes) was selected because most phyla are sequenced bidirectionally, even though many insects are now sequenced unidirectionally.
-Also, going with a shorter sequence will permit us to include more BINs.
-The length was standardized so that exactly the same genetic region will be compared across all tests.
