### ISSUE TITLE
Sally got an error on line 1610

### ISSUE THREAD

**Issue by sadamowi** [m-orton/Evolutionary-Rates-Analysis-Pipeline#21]
Hi Matt,

I also got an error when plotting, using the block of code starting on line 1610.

plot_ly(dfPairingResultsL1L2, lat = medianLatMap.x, lon = medianLon.x, text = hover,
+         color = as.ordered(inGroupPairing), colors = "Spectral", mode = "markers+lines", type = 'scattergeo') %>%
+   layout(title = paste0(mapTitle) , geo = mapLayout)

Error in plot_ly(dfPairingResultsL1L2, lat = medianLatMap.x, lon = medianLon.x,  : 
  object 'medianLatMap.x' not found

> plot_ly(dfPairingResultsL1L2, lat = medianLatMap.x, lon = medianLon.x, text = hover,
+         color = class_name.x, mode = "markers", type = 'scattergeo') %>%
+   layout(title = paste0(mapTitle) , geo = mapLayout)

Error in plot_ly(dfPairingResultsL1L2, lat = medianLatMap.x, lon = medianLon.x,  : 
  object 'medianLatMap.x' not found

>

**Comment by m-orton** [comment]
Hi Sally, upon updating R versions, I am now getting this error as well. I will let you know if I find a solution.

Matt

**Comment by sadamowi** [comment]
Update when running revised Annelida code using very very secure dishes.

Line is now 1634.

> plot_ly(dfPairingResultsL1L2, lat = medianLatMap, lon = medianLon, text = hoverText,
+         color = as.ordered(inGroupPairing), colors = "Spectral", mode = "markers+lines", type = 'scattergeo') %>%
+   layout(title = paste0(mapTitle) , geo = mapLayout)

Error in plot_ly(dfPairingResultsL1L2, lat = medianLatMap, lon = medianLon,  : 
  object 'hoverText' not found

**Comment by m-orton** [comment]
Hi Sally, I think I was able to fix the plotly command by adding a new line of code and changing the variables of the plotly command slightly.

Best Regards,
Matt

**Comment by m-orton** [comment]
Should mention that its this command at 1649:
attach(dfPairingResultsL1L2)

Best regards,
Matt

**Comment by m-orton** [comment]
I think Im going to close this issue since I have fixed this specific error with the plot,
