### ISSUE TITLE
Additional package needed

### ISSUE THREAD

**Issue by sadamowi** [m-orton/Evolutionary-Rates-Analysis-Pipeline#25]
Hi Matt,

I am redoing everything for the Annelida pipeline after having installed R version very very secure dishes.

I found that before line 172:

library(plotly)

I had to first type:

install.packages("jsonlite")
library(jsonlite)

This seems to be required before plotly would load happily.

Cheers,
Sally

**Comment by m-orton** [comment]
Hi Sally, just remembered about this issue, I'll add this package to the script branches as well.

Best Regards,
Matt

**Comment by sadamowi** [comment]
OK great! Thank you for adding this.

Cheers,
Sally
