### ISSUE TITLE
Update to Pipeline and New Branch

### ISSUE THREAD

**Issue by m-orton** [m-orton/Evolutionary-Rates-Analysis-Pipeline#35]
Hi Sally and Jacqueline,

This is more of an update rather than an issue so I can close this once everyone has seen it. 

Just letting you know I have updated all of the branches so that they can now run single classes and orders at a time. 

I also created a branch that is intended to be run with any of the classes/orders in Arthropoda but could be used as a template for other very large taxa. In running Lepidoptera, I've had to make some minor adjustments to the pipeline in order to minimize memory load, reduce workspace sizes (since saving workspaces has been vital in case of crashes) and improve processing speed (since some steps of the pipeline can be very time consuming). This version of the pipeline should allow very large datasets to be run more smoothly. Although, its probably not needed for the smaller phyla that can be run locally.

Best Regards,
Matt

**Comment by sadamowi** [comment]
Hi Matt,

Thank you very much for your work on these changes and for this update.

Best wishes,
Sally

**Comment by jmay29** [comment]
Nice! I will try it out on a single fish class over the weekend.

**Comment by m-orton** [comment]
Closing this issue since everyone has seen this now.
