### ISSUE TITLE
Error on line 1572 of Annelida branch

### ISSUE THREAD

**Issue by jmay29** [m-orton/Evolutionary-Rates-Analysis-Pipeline#38]
So, I got this error on line 1572:

> pValBinomialTitle <- foreach(i=1:length(pvalBinomialClass)) %do% 
 paste("Binomial Test p-value:", round(pvalBinomialClass[i], digits = 4))
Error in paste("Binomial Test p-value:", round(pvalBinomialClass[i], digits = 4)) : 
  task 1 failed - "non-numeric argument to mathematical function"

I seemed to have fixed it by changing pvalBinomialClass[i] to pvalBinomialClass[[i]] as pvalBinomialClass[i] is of the list class and pvalBinomialClass[[i]] is of numeric class. Please let me know if you guys come across the same error.

**Comment by jmay29** [comment]
The same thing would apply to line 1574:

> pvalWilcoxonTitle <- foreach(i=1:length(pvalBinomialClass)) %do% 
paste("Wilcoxon Test p-value:", round(pvalWilcoxonClass[i], digits = 4))
Error in paste("Wilcoxon Test p-value:", round(pvalWilcoxonClass[i], digits = 4)) : 
  task 1 failed - "non-numeric argument to mathematical function"

**Comment by m-orton** [comment]
Thanks Jacqueline, I'll let you know if I get the same error.

**Comment by m-orton** [comment]
Hi Jacqueline, I got the same error and was able to fix it by using your suggestion of changing to
pvalBinomialClass[[i]] and pvalWilcoxonClass[[i]].

**Comment by jmay29** [comment]
Ok awesome!! I guess we can close this issue then?

**Comment by m-orton** [comment]
Agreed, issue is fixed, closing.
