### ISSUE TITLE
Notes on Annelida branch

### ISSUE THREAD

**Issue by m-orton** [m-orton/Evolutionary-Rates-Analysis-Pipeline#4]
Just created a separate branch for Annelida. Purposely not merging to keep things separate. Not sure if the commit comments are showing up so Im posting here.

I think what I will do is make separate branches for each specific phyla so each phyla can be modified independently depending on specific changes that may need to be made for it.

Notes on changes made:
Reference sequence dataframe now has real reference sequences for Clitellata and Polychaeta
Minimum sequence length in filtering changed to 620 bp, maximum remains at 1000 and longer sequences will be trimmed down to reference length.
Symmetric trimming of the reference sequences - 19 bp on either end to a final sequence length of 620 for all sequences

Formatting changes to reflect that the analyses is being made at the class level instead of order level
Plot of relative outgroup distance now generated according to class
Pvalue dataframe now has total pvalues for binomial and wilcoxon as well as pvalues per class

Notes on Annelida analyses:
-seem to be running into some issues with the alignment for Polychaeta, some large gaps are present in the alignment
-the Clitellata alignment looks good though there is one indel apparent in the alignment

Sending results of Annelida shortly

**Comment by m-orton** [comment]
Just updated the Annelida branch with your changes Sally. I address all of the changes in the Commit comments.

Also, I did have the dplyr package installed on my RStudio from several months ago, I must have forgotten to add that in the packages section initially. Sorry about that.

**Comment by sadamowi** [comment]
Great! Thanks Matt. No worries about the extra packages. That is why I am running everything on a newly installed version of R... to test how this will work for a brand new user. Thank you for making these changes.
