### ISSUE TITLE
Map Figures

### ISSUE THREAD

**Issue by m-orton** [m-orton/Evolutionary-Rates-Analysis-Pipeline#44]
Hi Sally, I thought I would make an issue for discussing the map figures.

I looked into that one Echinoderm pair that was in the middle of Africa. It turns out its because the BIN that lineage belongs to only has two specimens; one at 28 degrees and another at 3 degrees in latitude (which both are on the coast of Africa) but when you take the median you get a point in the middle of Africa. Smaller BIN's like this could pose a problem for mapping so I suggest we only show pairings with BINs which are larger in size (say maybe 10 specimens/records or larger?) such that the median is more representative. I also like your idea of showing the pairings with the largest latitudinal differences. 

Let me know what you think,
Matt

**Comment by sadamowi** [comment]
Hi Matt,

Thank you very much for looking into that echinoderm pair found in inland Africa. I was hoping that the points themselves were legitimate, and that it was just the median that was inland. So, that is good that that was the case. I think plotting that point is OK, as long as we mention that point in the legend for the benefit of readers.

The decisions about this plot come down to what what are the main messages we want to convey?

Given that we will discuss the result for this taxon in more detail, my preference is to show all of the pairs. That African point is one of the modest number of points that includes a tropical member, and I think deleting such pairs would weaken the main message. In my view, we want to convey that there are multiple pairs that include a tropical member. There are two with one sister in Africa and several such pairs with a tropical member in the Australasian region. We will raise this point about the tropical pairs in the prose as well, and I think that the figure should reflect that.

Geographical distributions have shifted dramatically during the Holocene, particularly in formerly glaciated areas of the northern hemisphere (including both temperate and polar regions). Therefore, inclusion of pairs with a tropical member is very important for our main conclusions.

I realize that currently the display of the legend is less than ideal. Can the legend be turned into two columns? Alternatively, is it possible instead to create a legend that shows the latitudinal spread? e.g. categories such as: 20-30 latitudinal difference, 30-40, etc? (Absolute values would need to be used for the latitude spread.) This would give just a modest number of categories for the legend. This info could be helpful (even though the info can be discerned without a legend), given that it can be hard to quickly judge by eye quickly the differences in absolute latitude.

Another option would be to colour code the pairs by class.

Finally, we could remove the legend entirely.

I suggest all of the above options are preferable to dropping pairs.

What are your thoughts?

Best wishes,
Sally

**Comment by m-orton** [comment]
Hi Sally, I've been experimenting with various ways of presenting the class and lat difference on a map (lat difference between absolute median lat values). I put these maps in a folder called Mar8Maps in the Maps folder.

I figured out how to show the legend horizontally so that all items are shown in the legend however Im still struggling to show a legend title (its actually quite challenging to implement a legend title in plotly lol) Some maps I color coded by class, some I color coded by lat difference or lat difference range, some I used symbols for class and color for lat difference.  I also experimented with only showing points vs showing points and lines. 

Im sort of feeling like the lines make the maps too cluttered and that a map that only show points might be the way to go.

Let me know if any stand out to you and I can work more on those,
Matt

**Comment by sadamowi** [comment]
Hi Matt,

Very cool. Thank you for these additional plots. I have a few thoughts:

-I think that is good to include all pairs. I am pleased to see that there are more pairs with a tropical member.

-I think that we need the lines.

-I don't think that we need a legend title on the figure itself. We can include a comment about the graphical legend in the prose legend (which would be placed below the figure).

-I'd like to suggest to try the following two options (I do not currently see these combinations among those options you have tried so far).

a) all pairs, with lines. colour coded by class. I suggest to use a joint combination of colour/symbol for each class, such that the figure can also be interpreted by those with impaired colour vision.

b) Same as above, but coloured by lat difference. For this to make sense to do, we would need to use a small number of categories of lat difference, rather than trying to colour every single pair according to its lat difference. e.g. 20-30, 30-40, 40-50, etc. If this is quite tricky, then I suggest we have a look at option "a" first.

For the symbols, I find the square with the little x to add visual noise. I suggest to use basic shapes: e.g. circle, square, triangle, star, and perhaps a +? Also, is it possible to add a black outline around the shapes so that the shapes show up more clearly?

Thanks for considering these ideas.

Best wishes,
Sally

**Comment by m-orton** [comment]
Hi Sally,

I managed to implement a map that has lines color and symbol coded by latitudinal range between the following ranges: 20-30, 30-40, 40-50, 50-60 for Echinoderms. I actually couldn't figure out how to do this yesterday so thats why I didnt post this version then.

I've posted two versions that are similar in a folder Mar9Maps, one with natural earth and another with Kavrayskiy7 which are both quite similar but Kavrayskiy7 gives a little more space in the poles which might be good for Echinoderms. I also enlarged the symbols slightly that have fewer points to make them more visible and made the line widths smaller so that there is less overlap.

I posted a higher resolution version on my plotly here: https://plot.ly/~BIFIGP/20
So that you can zoom in on points if you want. 

Its actually quite challenging to color code by lat range (or class) since I have to manually color and symbol code each pairing (cant do it with commands due to limitations with plotly) but I'm ok with doing it for a few more groups if you like the maps. I'd like to suggest we go with coding by lat range since I've figured out how to do it and it would take more time to implement color code by class with lines. 

Best Regards,
Matt

**Comment by sadamowi** [comment]
Hi Matt,

I think that's very cool. I like the groupings by latitudinal difference, and I think that makes a lot of sense in terms of the scientific information to convey. Thank you very much for working how to do the codings that way.

So, now that the figure is made, can you change the colours by entire groupings or would this still need to be pair by pair?

Given the manual effort involved, I think we should think very carefully about any final group(s) that we might want a figure for before you spend that time on it. Perciformes does sound like a reasonable option, which I believe we discussed before?

For the candidate "overwhelming sample size" figure, I don't think we would do a legend at all, but I think we'd want lines to show emerging overall patterns. Have you tried building a plot of a very large taxonomic group to see how it looks?

In terms of the echinoderm plot, I like it a lot. The only thing is the colour choices. I found this link very interesting:

http://jfly.iam.u-tokyo.ac.jp/color/index.html

I have read on other links as well that magenta and turqouise are good colours for most people to distinguish. So, if each pair needs changing manually, then I suggest to leave the common category (20-30) and consider adjusting the colour of the less common categories.

I also found this link helpful for doing a check of the figure colours:

http://vischeck.com/vischeck/vischeckImage.php

The current version does not look very vivid when run through this online tool. Perhaps consider keeping the 20-30 as is and then using vermillion (adding some orange) for the current red, change the green to turqouise, and possibly use a very bright shade of magenta for the 50-60? What do you think?

Best wishes,
Sally

**Comment by sadamowi** [comment]
PS. I see your point about the map that gives more room around the poles. I agree.

**Comment by m-orton** [comment]
Glad you like the map! 

I see your point about the colors, I can change the colors pretty easily so I will try and improve upon the color selection based on what you have said. Actually looking at that article, maybe I could change the line to have a different shape depending on the range group? For example 20-30 could be dotted lines, 30-40 could be solid etc. Just another way to differentiate between groups of pairings.

As for other groups, I think Perciformes would be a good group to do also and then I think we would need a terrestrial group to balance things out. 

I have built plots for larger sample sizes and the amount of visual information is...overwhelming lol. I posted full Aves just to give you an idea of what I mean in the map folder. Though Aves does seem to be abundant in pairs with more tropical lineages.

**Comment by sadamowi** [comment]
Hi Matt,

That sounds good. I suggest to make the most abundant line type the simplest visually (e.g. 20-30 as solid lines). Then, you could also use another thickness or dotted or dashed patterning for the others.

I actually quite like the bird map in terms of information content. However, I suggest we might consider not making that one one of our primary targets. Many birds migrate, and to go more in depth on birds we would need to go into that issue more deeply. I think we will need to raise that briefly in the discussion as a caveat of our study.

So, I will think more about a primarily terrestrial group that could be good as a target for more in-depth exploration. What about an insect group? Do you have any particular other ideas at this point for targets?

Best wishes,
Sally

**Comment by sadamowi** [comment]
What about giving consideration to a zoomed-in view of a densely sampled group, such as Hymenoptera NA?

**Comment by sadamowi** [comment]
PS. From Wikipedia:

"Approximately 1800 of the world's 10,000 bird species are long-distance migrants."

**Comment by m-orton** [comment]
Hi Sally, I posted Hymenoptera NA, AUS, SA and EUREFR to the dropbox map folder as potential terrestrial groups we could use. I think SA looks good, there are quite a few points which are more tropical but its small enough that if I color coded by lat range, a person could probably make out most pairs without much difficulty. 

Let me know what you think,
Matt

**Comment by m-orton** [comment]
Hi Sally, I just added maps for Perciformes and Echinoderms with an updated color scheme coded to lat range to a Mar10Maps folder. 
Three traits are now coded to lat range: color, line type and symbol. I used these criteria for the maps:

Using figure 16 from http://jfly.iam.u-tokyo.ac.jp/color/index.html for color selection
(should be good for colorblind people)

20-30 - purple - changing to blue (0,114,178,1)
circle
line solid - size = 7
line width = 1

30-40 - green - changing to bluish green (0,158,115,1)
diamond - size = 8
line dashed (dash = 'dash',)
line width = 2

40-50 - currently red - changing to vermillion (213,94,0,1)
star - size = 9
line dotted (dash = 'dot',)
line width = 3

50-60 - blue - changing to reddish purple (204,121,167,1)
square - size = 9
line dash (dash = 'dashdot',)
line width = 3

map projection = Kavrayskiy7 (more space around poles)

Let me know what you think,
Matt

**Comment by sadamowi** [comment]
Hi Matt,

I think these look great! Thank you for your work on these.

If possible, I suggest to make the font of the legend larger. Also, I suggest to make the legend wider so that the line styles can be more clearly seen in the legend.

Other than that, I'd like to suggest that we work more on the results section before selecting a final figure to display. Possibly, North American Hymenoptera could be a great candidate. This dataset showcases the huge sample size and also a lot of pairs involving a tropical member.

Best wishes,
Sally

**Comment by m-orton** [comment]
Awesome, glad you like them! I looked at the changing the legend options, plotly is pretty limiting in terms of legend options so I might have to do a little bit of editing in photoshop to get the symbols to look good with the lines but that shouldn't be too hard to do. 

I agree on Hymenoptera NA, I think it would be a great one to show.

**Comment by sadamowi** [comment]
That sounds great Matt.

Jacqueline - Would you please also have a look at the figures in folder Mar10Maps (within folder Map Plots). Does everything make sense to you? Thanks.

Best wishes,
Sally

**Comment by jmay29** [comment]
Hello! Yes, I can take a look at these figures, no problem!!

**Comment by jmay29** [comment]
They look great! I was just going to mention about including a legend title and maybe make it a bit larger but these issues are already being discussed. Otherwise the colours look clear to me!

**Comment by sadamowi** [comment]
Thanks for having a look. It is good to have a fresh set of eyes look at figures to make sure they are clear.

Best wishes,
Sally

**Comment by m-orton** [comment]
Thanks Jacqueline, glad you like the maps! Going to try and improve the legend soon.

**Comment by m-orton** [comment]
This issue was moved to jmay29/lat-project#2
