### ISSUE TITLE
Error message when Sally running Annelida branch - line 869 - Nov 28

### ISSUE THREAD

**Issue by sadamowi** [m-orton/Evolutionary-Rates-Analysis-Pipeline#9]
Hi Matt,

I am running the Annelida branch, using the Annelida workspace you sent me. I got the following error when I ran line  869 of the code.

noOutGroupCheck <- foreach(i=1:length(noOutGroupCheck)) %do% which(dfPairingResultsL1$bin_uri == noOutGroupCheck[[i]])

Error in which(dfPairingResultsL1$bin_uri == noOutGroupCheck[[i]]) : 
  task 1 failed - "subscript out of bounds"

Have you seen this error before? Thanks.

Cheers,
Sally

**Comment by sadamowi** [comment]
I reran the script again, starting from a fresh RStudio session. I got this error message a second time.

**Comment by m-orton** [comment]
So just to confirm, you are not getting any errors now?

**Comment by sadamowi** [comment]
I closed a couple of the other issues, as I didn't get those errors when I reran the script. However, I did get this error again and so am leaving this open for now.

**Comment by m-orton** [comment]
Ok I will look into this error today and get back to you.

**Comment by sadamowi** [comment]
Email from Matt on this issue:

"That nooutgroupcheck variable that gave you an error also gave me an error as well. I realized it was because the variable was empty for Annelida which is why we were getting the subscript out of bounds error. I encased the command in an if statement so it will only run if there are in fact pairings that dont have outgroups."

**Comment by sadamowi** [comment]
Thank you Matt. I no longer get this error and your solution looks good. Thank you. I will close this issue.
